import {defineArrayMember, defineField, defineType} from 'sanity'

export const contactPageType = defineType({
  name: 'contactPage',
  title: 'Contact Page',
  type: 'document',
  groups: [
    {name: 'hero', title: 'Hero'},
    {name: 'inquiry', title: 'Project Inquiry'},
    {name: 'form', title: 'Form'},
    {name: 'referral', title: 'Strategic Intelligence'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({name: 'heroEyebrow', title: 'Hero Eyebrow', type: 'string', group: 'hero'}),
    defineField({name: 'heroHeadingTop', title: 'Hero Heading — Top', type: 'string', group: 'hero'}),
    defineField({name: 'heroHeadingAccent', title: 'Hero Heading — Accent', type: 'string', group: 'hero'}),
    defineField({name: 'heroIntro', title: 'Hero Intro', type: 'text', rows: 4, group: 'hero'}),
    defineField({name: 'inquiryEyebrow', title: 'Inquiry Eyebrow', type: 'string', group: 'inquiry'}),
    defineField({name: 'inquiryHeading', title: 'Inquiry Heading', type: 'string', group: 'inquiry'}),
    defineField({name: 'inquiryCopy', title: 'Inquiry Copy', type: 'text', rows: 5, group: 'inquiry'}),
    defineField({name: 'studioLabel', title: 'Studio Value', type: 'string', group: 'inquiry', description: 'Displayed beside the fixed “Studio” label.'}),
    defineField({name: 'establishedLabel', title: 'Established Value', type: 'string', group: 'inquiry', description: 'Displayed beside the fixed “Established” label.'}),
    defineField({name: 'projectTypesSummary', title: 'Project Types Summary', type: 'string', group: 'inquiry'}),
    defineField({name: 'projectTypePrompt', title: 'Project Type Prompt', type: 'string', group: 'form', description: 'Heading above the project-type choices.'}),
    defineField({name: 'projectTypes', title: 'Project Types', type: 'array', group: 'form', of: [defineArrayMember({type: 'string'})]}),
    defineField({name: 'budgetOptions', title: 'Budget Options', type: 'array', group: 'form', of: [defineArrayMember({type: 'string'})]}),
    defineField({name: 'timelineOptions', title: 'Timeline Options', type: 'array', group: 'form', of: [defineArrayMember({type: 'string'})]}),
    defineField({name: 'sourceOptions', title: 'How They Found Us', type: 'array', group: 'form', of: [defineArrayMember({type: 'string'})]}),
    defineField({
      name: 'formFields',
      title: 'Visible Form Fields',
      type: 'array',
      group: 'form',
      of: [defineArrayMember({
        type: 'object',
        fields: [
          defineField({name: 'label', title: 'Label', type: 'string'}),
          defineField({name: 'name', title: 'Field Name', type: 'string'}),
          defineField({name: 'inputType', title: 'Input Type', type: 'string'}),
          defineField({name: 'placeholder', title: 'Placeholder', type: 'string'}),
          defineField({name: 'required', title: 'Required', type: 'boolean'}),
        ],
        preview: {select: {title: 'label', subtitle: 'name'}},
      })],
    }),
    defineField({name: 'submitLabel', title: 'Submit Button Label', type: 'string', group: 'form'}),
    defineField({name: 'formNote', title: 'Form Note', type: 'string', group: 'form'}),
    defineField({name: 'successMessage', title: 'Form Success Message', type: 'string', group: 'form'}),
    defineField({name: 'errorMessage', title: 'Form Error Message', type: 'string', group: 'form'}),
    defineField({name: 'referralEyebrow', title: 'Referral Eyebrow', type: 'string', group: 'referral'}),
    defineField({name: 'referralHeading', title: 'Referral Heading', type: 'string', group: 'referral'}),
    defineField({name: 'referralCopy', title: 'Referral Copy', type: 'text', rows: 4, group: 'referral'}),
    defineField({name: 'referralLabel', title: 'Referral Link Label', type: 'string', group: 'referral'}),
    defineField({name: 'referralUrl', title: 'Referral URL', type: 'url', group: 'referral'}),
    defineField({name: 'seo', title: 'SEO', type: 'seoFields', group: 'seo'}),
  ],
  preview: {prepare: () => ({title: 'Contact Page'})},
})
