import {defineArrayMember, defineField, defineType} from 'sanity'

export const portfolioProjectType = defineType({
  name: 'portfolioProject',
  title: 'Portfolio Project',
  type: 'document',
  groups: [
    {name: 'identity', title: 'Project'},
    {name: 'story', title: 'Case Study'},
    {name: 'evidence', title: 'Evidence'},
    {name: 'media', title: 'Media'},
    {name: 'publishing', title: 'Publishing'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({name: 'title', title: 'Project Title', type: 'string', group: 'identity', validation: (Rule) => Rule.required()}),
    defineField({name: 'slug', title: 'Slug', type: 'slug', options: {source: 'title', maxLength: 96}, group: 'identity', validation: (Rule) => Rule.required()}),
    defineField({name: 'client', title: 'Client', type: 'reference', to: [{type: 'client'}], group: 'identity'}),
    defineField({name: 'clientNameOverride', title: 'Client Name Override', type: 'string', group: 'identity'}),
    defineField({name: 'discipline', title: 'Discipline', type: 'string', group: 'identity'}),
    defineField({name: 'cardCategoryLabel', title: 'Card Category Label', type: 'string', group: 'identity'}),
    defineField({name: 'cardCopy', title: 'Card Supporting Copy', type: 'text', rows: 3, group: 'identity'}),
    defineField({
      name: 'portfolioLevel',
      title: 'Portfolio Level',
      type: 'string',
      group: 'identity',
      options: {
        list: [
          {title: 'Featured Project', value: 'featured'},
          {title: 'Case Study', value: 'caseStudy'},
          {title: 'Portfolio Artifact', value: 'artifact'},
        ],
        layout: 'radio',
      },
      initialValue: 'artifact',
    }),
    defineField({name: 'summary', title: 'Project Summary', type: 'text', rows: 4, group: 'story'}),
    defineField({
      name: 'challenge',
      title: 'Challenge',
      type: 'text',
      rows: 5,
      group: 'story',
      description: 'The documented communication, brand, information or experience problem this project needed to address.',
    }),
    defineField({
      name: 'strategy',
      title: 'Strategic Reasoning',
      type: 'text',
      rows: 6,
      group: 'story',
      description: 'How the work was organized or approached. Keep claims grounded in the project record.',
    }),
    defineField({
      name: 'designSystem',
      title: 'System / Solution',
      type: 'text',
      rows: 6,
      group: 'story',
      description: 'What was actually designed or built.',
    }),
    defineField({name: 'portfolioTreatment', title: 'Portfolio Treatment / Editorial Note', type: 'text', rows: 5, group: 'evidence'}),
    defineField({name: 'deliverables', title: 'Deliverables', type: 'array', group: 'story', of: [defineArrayMember({type: 'string'})]}),
    defineField({
      name: 'outcomes',
      title: 'Documented Design / Communication Outcomes',
      type: 'array',
      group: 'evidence',
      description: 'Qualitative or quantitative outcomes that can be supported by the available project evidence. Do not infer business performance.',
      of: [defineArrayMember({type: 'string'})],
    }),
    defineField({
      name: 'evidenceStatus',
      title: 'Evidence Status',
      type: 'string',
      group: 'evidence',
      options: {
        list: [
          {title: 'Documented Case Study', value: 'documented'},
          {title: 'Partial Evidence / Expandable', value: 'partial'},
          {title: 'Portfolio Artifact', value: 'artifact'},
        ],
        layout: 'radio',
      },
    }),
    defineField({
      name: 'evidenceNote',
      title: 'Evidence Note',
      type: 'text',
      rows: 4,
      group: 'evidence',
      description: 'Internal editorial note describing what is documented and what still needs assets, narrative or metrics.',
    }),
    defineField({
      name: 'metrics',
      title: 'Documented Metrics',
      type: 'array',
      group: 'evidence',
      description: 'Only use metrics that can be substantiated.',
      of: [defineArrayMember({
        type: 'object',
        fields: [
          defineField({name: 'label', title: 'Metric', type: 'string'}),
          defineField({name: 'value', title: 'Value', type: 'string'}),
        ],
        preview: {select: {title: 'value', subtitle: 'label'}},
      })],
    }),
    defineField({name: 'website', title: 'Project / Live Website URL', type: 'url', group: 'identity'}),
    defineField({name: 'coverImage', title: 'Cover Image', type: 'image', options: {hotspot: true}, group: 'media'}),
    defineField({name: 'legacyCoverPath', title: 'Current Site Media Path', type: 'string', group: 'media', readOnly: true}),
    defineField({
      name: 'gallery',
      title: 'Project Gallery',
      type: 'array',
      group: 'media',
      of: [defineArrayMember({type: 'image', options: {hotspot: true}, fields: [defineField({name: 'alt', title: 'Alt Text', type: 'string'})]})],
    }),
    defineField({name: 'legacyAccent', title: 'Current Accent Color', type: 'string', group: 'publishing', readOnly: true}),
    defineField({name: 'featured', title: 'Feature on Portfolio Page', type: 'boolean', initialValue: false, group: 'publishing'}),
    defineField({name: 'featuredOrder', title: 'Featured Order', type: 'number', group: 'publishing'}),
    defineField({name: 'portfolioOrder', title: 'Portfolio Index Order', type: 'number', group: 'publishing'}),
    defineField({name: 'publishedAt', title: 'Published Date', type: 'datetime', group: 'publishing'}),
    defineField({name: 'seo', title: 'SEO', type: 'seoFields', group: 'seo'}),
  ],
  orderings: [
    {title: 'Portfolio Order', name: 'portfolioOrder', by: [{field: 'portfolioOrder', direction: 'asc'}]},
    {title: 'Featured Order', name: 'featuredOrder', by: [{field: 'featuredOrder', direction: 'asc'}]},
  ],
  preview: {
    select: {
      title: 'title',
      client: 'client.name',
      clientOverride: 'clientNameOverride',
      media: 'coverImage',
      discipline: 'discipline',
      evidenceStatus: 'evidenceStatus',
    },
    prepare: ({title, client, clientOverride, media, discipline, evidenceStatus}) => ({
      title,
      subtitle: [clientOverride || client, discipline, evidenceStatus].filter(Boolean).join(' · '),
      media,
    }),
  },
})
